### ISSUE TITLE
Test Utils demo should have an actual test using test-utils

### ISSUE THREAD

**Issue by BlakeTheAwesome** [lmiller1990/vtu-next-demo#2]
This repository currently has a jest script to execute tests, but no examples of passing tests that make use of the test utils.

This means you can't verify that the test utils framework is actually loaded correctly.

**Comment by lmiller1990** [comment]
Good idea. I will add this.

If you want a more full example, you can see [here](https://github.com/lmiller1990/vuejs-composition-course) (make sure to look at the latest branch, around 5.3 or so). This is a course on testing I'm working on, which has some examples and is forked from this repo.

**Comment by lmiller1990** [comment]
Done

https://github.com/lmiller1990/vtu-next-demo/commit/088ef38af724720e6cd672baa5a665386db472bf
